import { Geist,Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SummerMarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` ${geistMono.variable} h-full antialiased`}
      data-theme="light"
    >
      <body className={inter.className}>
        <Navbar></Navbar>
        <main>
            {children}
        </main>
      <Footer></Footer>
        </body>
    </html>
  );
}
